---
apiVersion: v2
name: airflow-operator
version: "24.7.0"
appVersion: "24.7.0"
description: The Stackable Operator for Apache Airflow
home: https://github.com/stackabletech/airflow-operator
maintainers:
  - name: Stackable
    url: https://www.stackable.tech
