[package]
authors = ["Stackable GmbH <info@stackable.de>"]
description = "Contains the Apache Airflow CRD structs and utilities"
edition = "2021"
license = "OSL-3.0"
name = "stackable-airflow-crd"
repository = "https://github.com/stackabletech/airflow-operator"
version = "0.3.0-nightly"

[dependencies]
serde = "1.0"
serde_json = "1.0"
stackable-operator = { git = "https://github.com/stackabletech/operator-rs.git", branch = "main" }
strum = { version = "0.23", features = ["derive"] }
strum_macros = "0.23"

[dev-dependencies]
serde_yaml = "0.8"